version: '3.7'

services:
  postgres:
    build: .\
    container_name: postgres_fmp
    hostname: postgres_fmp
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fmp
    volumes:
      - postgres_fmp_data://var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_fmp
    hostname: pgadmin_fmp
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    volumes:
      - pgadmin_config_fmp_data:/pgadmin4
      - pgadmin_fmp_data:/var/lib/pgadmin
    ports:
      - "6003:80"
    depends_on:
      - postgres
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_fmp_data:
  pgadmin_config_fmp_data:
  pgadmin_fmp_data:
